version: "3"

services:

    nginx:
      container_name: nginx
      image: nginx:latest
      ports:
          - "8082:80"
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    symfony-app:
        container_name: symfony-app
        build: docker/php
        ports:
            - "8006:8000"
        working_dir: /application
        volumes:
            - .:/application

    mysql-db:
        container_name: mysql-db
        image: mysql:latest
        volumes:
            - symfony-db-data:/var/lib/mysql
        ports:
            - "8007:3306"
        environment:
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_DATABASE: symfony
            MYSQL_ROOT_PASSWORD: root

volumes:
  symfony-db-data:
