version: "3"

services:

    symfony-nginx:
      container_name: symfony-nginx
      image: nginx:latest
      ports:
          - "8082:80"
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    symfony-app:
        container_name: symfony-app
        build: docker/php
        ports:
            - "8006:8000"
        working_dir: /application
        volumes:
            - .:/application

    symfony-db:
        container_name: symfony-db
        image: postgres:12.0-alpine
#        volumes:
#            - symfony-db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
            POSTGRES_DB: symfony

#volumes:
#  symfony-db-data: