app_auto_get_list_car:
    path: /auto
    controller: App\Controller\AutoController::getListCar

#cars_list:
#    # Matches /cars exactly
#    path:     /blog
#    controller: App\Controller\AutoController::list
#
#cars_show:
#    # Matches /cars/*
#    # but not /cars/id/extra-part
#    path:     /cars/{id}
#    controller: App\Controller\AutoController::show

about_car:
    path:
        nl: /over-car
        en: /about-car
    controller: App\Controller\AutoController::about