<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMIz50lC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMIz50lC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMIz50lC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMIz50lC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMIz50lC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MIz50lC',
    'container.build_id' => 'dfef9afe',
    'container.build_time' => 1563467714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMIz50lC');
