<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC3dIYyI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC3dIYyI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC3dIYyI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC3dIYyI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerC3dIYyI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'C3dIYyI',
    'container.build_id' => 'cf87ebc6',
    'container.build_time' => 1563909592,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC3dIYyI');
