<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_auto_getlistnewrouting.en' => [[], ['_controller' => 'App\\Controller\\AutoController::getListNewRouting', '_locale' => 'en', '_canonical_route' => 'app_auto_getlistnewrouting'], [], [['text', '/route/auto']], [], []],
    'app_auto_getlistnewrouting.nl' => [[], ['_controller' => 'App\\Controller\\AutoController::getListNewRouting', '_locale' => 'nl', '_canonical_route' => 'app_auto_getlistnewrouting'], [], [['text', '/nl/route/auto']], [], []],
    'cars_list.en' => [[], ['_controller' => 'App\\Controller\\AutoController::list', '_locale' => 'en', '_canonical_route' => 'cars_list'], [], [['text', '/cars']], [], []],
    'cars_list.nl' => [[], ['_controller' => 'App\\Controller\\AutoController::list', '_locale' => 'nl', '_canonical_route' => 'cars_list'], [], [['text', '/nl/cars']], [], []],
    'cars_show.en' => [['slug'], ['_controller' => 'App\\Controller\\AutoController::show', '_locale' => 'en', '_canonical_route' => 'cars_show'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/cars']], [], []],
    'cars_show.nl' => [['slug'], ['_controller' => 'App\\Controller\\AutoController::show', '_locale' => 'nl', '_canonical_route' => 'cars_show'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/nl/cars']], [], []],
    'cars_about.en' => [['id'], ['id' => '220', '_controller' => 'App\\Controller\\AutoController::aboutCar', '_locale' => 'en', '_canonical_route' => 'cars_about'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/cars']], [], []],
    'cars_about.nl' => [['id'], ['id' => '220', '_controller' => 'App\\Controller\\AutoController::aboutCar', '_locale' => 'nl', '_canonical_route' => 'cars_about'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/nl/cars']], [], []],
    'app_auto_get_list_car' => [[], ['_controller' => 'App\\Controller\\AutoController::getListCar'], [], [['text', '/auto']], [], []],
    'about_car.nl' => [[], ['_controller' => 'App\\Controller\\AutoController::about', '_locale' => 'nl', '_canonical_route' => 'about_car'], [], [['text', '/over-car']], [], []],
    'about_car.en' => [[], ['_controller' => 'App\\Controller\\AutoController::about', '_locale' => 'en', '_canonical_route' => 'about_car'], [], [['text', '/about-car']], [], []],
];
